- name: install and configure web server
  hosts: web
  tasks:
  - name: install nginx package
    yum:  
      name: nginx
      state: present
  - name: open 80 port
    firewalld:
      service: http
      state: enabled
      immediate: yes
      permanent: yes
  - name: copy index.k2 
    template:
      src: index.j2
      dest: /usr/share/nginx/html/index.html
  - name: copy nginx.j2
    template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx
  - name: 
    service: 
      name: nginx
      state: started
      enabled: yes
  handlers:
  - name: restart nginx
    service: 
      name: nginx
      state: reloaded 
