- name: install and configure load balancer on control node
  vars_files: vars_web
  hosts: all
  tasks:
  - name: install web package (nginx)
    yum:
      name: nginx
      state: present
  - name: Open http port on firewalld
    firewalld:
      service: http
      state: enabled
      permanent: yes
      immediate: yes
  - name: copy nginx.conf
    template:
      src: nginx.j2
      dest: /etc/nginx/nginx.conf
    when: ansible_hostname == "control"
    notify: restart
  - name: Start and enable nginx service
    service:
      name: nginx
      state: started
      enabled: yes
  handlers:
  - name: restart
    service:
      name: nginx
      state: restarted
     
